### ISSUE TITLE
AssertionError: Attribute 'thing_classes' in the metadata of 'xxx' cannot be set to a different value!

### ISSUE THREAD

**Issue by eronez** [ayushjain1144/odin#6]
```python
Number of datasets:  1
Traceback (most recent call last):
  File "/home/user/projects/Paper-Reproduction/odin/train_odin.py", line 605, in <module>
    launch(
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/user/projects/Paper-Reproduction/odin/train_odin.py", line 592, in main
    trainer = Trainer(cfg)
  File "/home/user/projects/Paper-Reproduction/odin/train_odin.py", line 119, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/user/projects/Paper-Reproduction/odin/train_odin.py", line 244, in build_train_loader
    dataset_dict = get_detection_dataset_dicts(
  File "/home/user/projects/Paper-Reproduction/odin/odin/data_video/build.py", line 132, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/user/projects/Paper-Reproduction/odin/odin/data_video/build.py", line 132, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/home/user/projects/Paper-Reproduction/odin/odin/data_video/datasets/scannet_context.py", line 202, in <lambda>
    DatasetCatalog.register(name, lambda: load_scannet_json_single(json_file, image_root, name))
  File "/home/user/projects/Paper-Reproduction/odin/odin/data_video/datasets/scannet_context.py", line 159, in load_scannet_json_single
    image_dataset = load_coco_json(
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/detectron2/data/datasets/coco.py", line 85, in load_coco_json
    meta.thing_classes = thing_classes
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/detectron2/data/catalog.py", line 148, in __setattr__
    assert oldval == val, (
AssertionError: Attribute 'thing_classes' in the metadata of 'scannet_context_instance_train_20cls_single_highres_100k' cannot be set to a different value!
['cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 'window', 'bookshelf', 'picture', 'counter', 'desk', 'curtain', 'refridgerator', 'shower curtain', 'toilet', 'sink', ' bathtub', 'otherfurniture', 'wall', 'floor'] != ['cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 'window', 'bookshelf', 'picture', 'counter', 'desk', 'curtain', 'refridgerator', 'shower curtain', 'toilet', 'sink', ' bathtub', 'otherfurniture']
```

While trying to run ```./scripts/scannet/scannet_resnet.sh```,it shows errors info as above.

Before I run this, I do some operations below:
1. Download ScanNet Dataset
2. Processing by ```python data_preparation/scannet/scannet_preprocessing.py preprocess --data_dir PATH_TO_RAW_SCANS --save_dir SAVE_DATA```
3. Download preprocessed RGB-D data and put it to corresponding dir
4. generate coco's json ```python data_preparation/scannet/scannet2coco.py```, there are many invalid pose tips, such as

> invalid pose: scene0685_02/pose/2900.txt
> invalid pose: scene0685_02/pose/2360.txt
> invalid pose: scene0685_02/pose/2380.txt
> invalid pose: scene0685_02/pose/2400.txt

but I think it's NOT the reason why AssertionError occurs.

Thank you for your help.

**Comment by ayushjain1144** [comment]
i pushed a fix, please re-run `python data_preparation/scannet/scannet2coco.py` and let me know if it doesn't fix the issue -- i can test it tomorrow on my side. 

"there are many invalid pose tips" : yes that's expected, some of the scannet poses have invalid values. and as you said, it isn't the cause of the issue.

**Comment by eronez** [comment]
> i pushed a fix, please re-run `python data_preparation/scannet/scannet2coco.py` and let me know if it doesn't fix the issue -- i can test it tomorrow on my side.
> 
> "there are many invalid pose tips" : yes that's expected, some of the scannet poses have invalid values. and as you said, it isn't the cause of the issue.

Yes,it has been fixed.
