### ISSUE TITLE
stack expects each tensor to be equal size

### ISSUE THREAD

**Issue by eronez** [ayushjain1144/odin#7]
```python
[05/20 15:09:59 d2.evaluation.evaluator]: Start inference on 156 batches
Traceback (most recent call last):
  File "/home/user/projects/Paper-Reproduction/odin/train_odin.py", line 605, in <module>
    launch(
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/user/projects/Paper-Reproduction/odin/train_odin.py", line 587, in main
    res = Trainer.test(cfg, model)
  File "/home/user/projects/Paper-Reproduction/odin/train_odin.py", line 455, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/detectron2/evaluation/evaluator.py", line 165, in inference_on_dataset
    outputs = model(inputs)
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/projects/Paper-Reproduction/odin/odin/odin_model.py", line 884, in forward
    depths, poses, valids, segments, intrinsics, multiview_data = self.load_3d_data(
  File "/home/user/projects/Paper-Reproduction/odin/odin/odin_model.py", line 253, in load_3d_data
    depths = torch.stack(
RuntimeError: stack expects each tensor to be equal size, but got [83, 240, 320] at entry 0 and [68, 240, 320] at entry 1
```
try to eval, I just modify scannet_resnet.sh as below:
```python
OMP_NUM_THREADS=8 CUDA_VISIBLE_DEVICES=0 python train_odin.py  --dist-url='tcp://127.0.0.1:8474' --num-gpus 1  --resume --config-file configs/scannet_context/3d.yaml --eval-only \
...
MODEL.WEIGHTS '/home/user/projects/Paper-Reproduction/odin/checkpoints/scannet_resnet_47.8_73.3_32k_1.5k.pth' \
...
```
But get errors,thanks for your assistance.

**Comment by ayushjain1144** [comment]
Hi, you would need to set SOLVER.TEST_IMS_PER_BATCH to 1 (I suspect you are using 1 GPU). 


(From the README)
SOLVER.TEST_IMS_PER_BATCH controls the (effective) test batch size. Since, there are variable numbers of images in a scene, we use bs=1 per GPU at test time.

**Comment by eronez** [comment]
Thank you. It's very helpful.
