### ISSUE TITLE
AttributeError: TEST_CLASS_AGNOSTIC

### ISSUE THREAD

**Issue by eronez** [ayushjain1144/odin#8]
```python
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/detectron2/data/common.py", line 125, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/user/projects/Paper-Reproduction/odin/odin/data_video/dataset_mapper_scannet.py", line 651, in __call__
    if self.cfg.TEST_CLASS_AGNOSTIC and not self.is_train:
  File "/home/user/anaconda3/envs/odin/lib/python3.10/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: TEST_CLASS_AGNOSTIC

  ```
  when run ai2thor_resnet.sh,it shows info above.cfg doesnot have this attribute.
  There are no things like "TEST_CLASS_AGNOSTIC" in project and library.
  How to solve this issue?

**Comment by ayushjain1144** [comment]
Hi @eronez, i pushed a fix. thanks for letting me know.

i appreciate you reporting these bugs! we are still in the process of verifying that our data setup and code runs properly, and we plan to be done by this weekend, sorry for the inconvinience. but in the meantime, please feel free to keep reporting these bugs :)

**Comment by eronez** [comment]
Solved.Thanks.
